version: '3.8'
services:
  katana:
    container_name: katana
    build:
      dockerfile: katana.Dockerfile
    ports:
      - 5050:5050
  postgres:
    container_name: postgres
    image: postgres:14.6
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=explorer
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./docker-data/postgres/data:/var/lib/postgresql/data/
  explorer:
    container_name: explorer
    build:
      dockerfile: explorer.Dockerfile
    env_file:
      - ./.env.explorer
    ports:
      - 4000:4000
    depends_on:
      - postgres
      - katana

networks:
  default:
    driver: bridge
  close:
    driver: bridge

volumes:
  pgadmin_data:
